# Generated by Django 5.2.13 on 2026-04-16 07:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('type_label', models.CharField(max_length=100)),
                ('capacity_label', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('amenities', models.JSONField(default=list)),
                ('contact', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status'], name='venues_venu_status_d850d5_idx'), models.Index(fields=['name'], name='venues_venu_name_6dcdaa_idx')],
            },
        ),
    ]
