# Generated by Django 5.2.12 on 2026-04-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='venue',
            name='contact',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
