# Generated by Django 5.2.12 on 2026-04-18 13:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_alter_venue_amenities_alter_venue_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Venue Category',
                'verbose_name_plural': 'Venue Categories',
            },
        ),
        migrations.RemoveField(
            model_name='venue',
            name='type_label',
        ),
        migrations.AddField(
            model_name='venue',
            name='campus_block',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='floor_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='full_description',
            field=models.TextField(blank=True, help_text='Detailed information, rules, and specifics.'),
        ),
        migrations.AddField(
            model_name='venue',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='venues/hero/'),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_publicly_available',
            field=models.BooleanField(default=True, help_text='Allow venue to be booked in the student portal.'),
        ),
        migrations.AddField(
            model_name='venue',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='venue',
            name='manager_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='venue',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='venue',
            name='max_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='nearby_landmarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='short_description',
            field=models.TextField(blank=True, help_text='A brief summary for card previews.'),
        ),
        migrations.AddField(
            model_name='venue',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='venues/thumbs/'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity_label',
            field=models.CharField(blank=True, help_text="e.g., '1,200 Seats'", max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='venue',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to='venues.venuecategory'),
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='venues/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Venue Gallery Image',
                'verbose_name_plural': 'Venue Gallery Images',
            },
        ),
    ]
