# Generated by Django 5.2.12 on 2026-04-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_venuecategory_remove_venue_type_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venuecategory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Venue Category', 'verbose_name_plural': 'Venue Categories'},
        ),
        migrations.AlterModelOptions(
            name='venueimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Venue Gallery Image', 'verbose_name_plural': 'Venue Gallery Images'},
        ),
        migrations.AddField(
            model_name='venue',
            name='google_maps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='map_coordinates',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
