# Generated by Django 5.2.13 on 2026-04-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_alter_venuecategory_options_alter_venueimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
