# Generated by Django 5.2.13 on 2026-05-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_alter_venue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['-created_at'], 'permissions': [('manage_venue', 'Can manage venues'), ('manage_venue_gallery', 'Can manage venue gallery images')], 'verbose_name': 'Venue', 'verbose_name_plural': 'Venues'},
        ),
    ]
