# Generated by Django 5.2.13 on 2026-04-18 11:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0005_user_dorm_block_user_dorm_room_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_staff_role', models.BooleanField(default=False, help_text='Should users with this role have admin panel access?')),
                ('group', models.OneToOneField(help_text='The Django Group that manages permissions for this role.', on_delete=django.db.models.deletion.CASCADE, related_name='role_profile', to='auth.group')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='old_role_temp',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='old_role_temp',
        ),
    ]
