# Generated by Django 5.2.13 on 2026-04-18 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0006_create_role_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='group',
            field=models.OneToOneField(blank=True, help_text='The Django Group that manages permissions for this role.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_profile', to='auth.group'),
        ),
    ]
