# Generated by Django 5.2.13 on 2026-04-16 07:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming Event'), ('live-now', 'Happening Now'), ('archived', 'Past Event')], default='upcoming', max_length=20)),
                ('is_mega_event', models.BooleanField(default=False)),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('schedule_date', models.DateField()),
                ('schedule_time_range', models.CharField(max_length=100)),
                ('about_paragraphs', models.JSONField(default=list)),
                ('attendance', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
