# Generated by Django 5.2.13 on 2026-04-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_cover_image_url_event_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='about_paragraphs',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='', help_text='Rich text content (HTML)'),
            preserve_default=False,
        ),
    ]
