# Generated by Django 5.2.12 on 2026-04-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_about_paragraphs_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendance',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
