# Generated by Django 5.2.12 on 2026-04-18 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_clubcategory_remove_club_category_label_and_more'),
        ('events', '0005_alter_event_attendance'),
        ('venues', '0002_alter_venue_amenities_alter_venue_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVolunteer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Event Volunteer',
                'verbose_name_plural': 'Event Volunteers',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_schedul_73b94c_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='schedule_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='schedule_time_range',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='logistics',
            field=models.JSONField(blank=True, default=list, help_text='List of EventLogisticsPoint'),
        ),
        migrations.AddField(
            model_name='event',
            name='physical_location_details',
            field=models.TextField(blank=True, help_text='e.g. Block 45, Second floor, Room 204'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date_time'], name='events_even_start_d_9d66c8_idx'),
        ),
        migrations.AddField(
            model_name='eventvolunteer',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='events.event'),
        ),
    ]
