# Generated by Django 5.2.12 on 2026-04-18 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_clubcategory_remove_club_category_label_and_more'),
        ('events', '0006_eventvolunteer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='clubs.clubcategory'),
        ),
    ]
