# Generated by Django 5.2.13 on 2026-04-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
    ]
