# Generated by Django 5.2.12 on 2026-04-18 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventvolunteer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='eventvolunteer',
            name='phone',
        ),
        migrations.AddField(
            model_name='eventvolunteer',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The registered user volunteering for this event.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_volunteering', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventvolunteer',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='eventvolunteer',
            name='student_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
