# Generated by Django 5.2.12 on 2026-04-18 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_eventvolunteer_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='summary',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='event',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='max_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventvolunteer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='eventvolunteer',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='eventvolunteer',
            name='role',
            field=models.CharField(blank=True, help_text='e.g. Usher, Coordinator', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventvolunteer',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The registered user volunteering for this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_volunteering', to=settings.AUTH_USER_MODEL),
        ),
    ]
