# Generated by Django 5.2.12 on 2026-04-30 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_event'),
        ('events', '0010_rename_summary_event_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_events', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_capacity',
            field=models.BigIntegerField(default=0),
        ),
    ]
