# Generated by Django 5.2.13 on 2026-05-02 19:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0012_remove_user_role_user_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('notification_type', models.CharField(choices=[('system', 'System'), ('alert', 'Alert'), ('booking', 'Booking'), ('announcement', 'Announcement'), ('security', 'Security')], default='system', max_length=30)),
                ('icon_key', models.CharField(blank=True, max_length=60)),
                ('href', models.CharField(blank=True, max_length=255)),
                ('target_all_users', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_system_notifications', to=settings.AUTH_USER_MODEL)),
                ('target_roles', models.ManyToManyField(blank=True, related_name='system_notifications', to='users.role')),
                ('target_users', models.ManyToManyField(blank=True, related_name='targeted_system_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Notification',
                'verbose_name_plural': 'System Notifications',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_read_states', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='core.systemnotification')),
            ],
            options={
                'verbose_name': 'Notification Read State',
                'verbose_name_plural': 'Notification Read States',
            },
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['is_active', 'created_at'], name='core_system_is_acti_f4f615_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['notification_type'], name='core_system_notific_056a13_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['expires_at'], name='core_system_expires_9aa32c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationreadstate',
            index=models.Index(fields=['user', 'read_at'], name='core_notifi_user_id_16a938_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationreadstate',
            index=models.Index(fields=['notification', 'user'], name='core_notifi_notific_26ee6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationreadstate',
            constraint=models.UniqueConstraint(fields=('notification', 'user'), name='core_notification_user_read_unique'),
        ),
    ]
