# Generated by Django 5.2.13 on 2026-05-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDashboardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='analytics', max_length=50, unique=True)),
            ],
            options={
                'permissions': [('view_analytics', 'Can view analytics dashboard')],
                'default_permissions': (),
            },
        ),
    ]
