"""
Django settings for aastu_su_backend project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-7x3@n69x+2bnm*6e%ely)hq7s^9oezo6#@=34utzur!5ufkaxe')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Allow explicitly enabling API documentation in non-debug environments
SERVE_API_DOCS = os.getenv('SERVE_API_DOCS', 'False') == 'True'

_default_allowed_hosts = [
    'localhost',
    '127.0.0.1',
    '.onrender.com',
    'aastu-student-union-web.vercel.app',
    'aastu-student-union-backend.onrender.com',
]
_configured_allowed_hosts = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', '').split(',')
    if host.strip()
]
ALLOWED_HOSTS = sorted(set(_default_allowed_hosts + _configured_allowed_hosts))


# Application definition

INSTALLED_APPS = [
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'django_filters',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'cloudinary',
    'cloudinary_storage',


    # Local apps
    'users',
    'clubs',
    'venues',
    'bookings',
    'events',
    'announcements',
    'core',
    'analytics',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Allow same-origin iframes so Jazzmin related-object modal forms (+ icon) can render.
X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'aastu_su_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aastu_su_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite configuration is kept for reference only.
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

def _build_database_config():
    database_url = os.getenv('DATABASE_URL', '').strip()
    if database_url:
        parsed = urlparse(database_url)
        if parsed.scheme in {'postgres', 'postgresql'}:
            query_params = parse_qs(parsed.query)
            sslmode = query_params.get('sslmode', [''])[0].strip() or os.getenv('DATABASE_SSLMODE', '').strip()
            config: dict[str, object] = {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': unquote(parsed.path.lstrip('/')),
                'USER': unquote(parsed.username or ''),
                'PASSWORD': unquote(parsed.password or ''),
                'HOST': parsed.hostname or 'localhost',
                'PORT': str(parsed.port or '5432'),
            }
            if sslmode:
                config['OPTIONS'] = {'sslmode': sslmode}
            return config

    host = os.getenv('DATABASE_HOST', 'localhost')
    default_sslmode = 'require' if host not in {'localhost', '127.0.0.1', ''} else ''
    sslmode = os.getenv('DATABASE_SSLMODE', default_sslmode).strip()

    config: dict[str, object] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DATABASE_NAME', 'aastu_su'),
        'USER': os.getenv('DATABASE_USER', 'postgres'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD', ''),
        'HOST': host,
        'PORT': os.getenv('DATABASE_PORT', '5432'),
    }
    if sslmode:
        config['OPTIONS'] = {'sslmode': sslmode}
    return config


DATABASES = {
    'default': _build_database_config(),
}

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'users.backends.MultiIdentifierBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# In production we serve static files via WhiteNoise. Keep a trailing slash on
# `STATIC_URL` and use a separate `STATIC_ROOT` directory for collected files.
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Optional: project-level static dirs (add if you have local `static/` folders)
STATICFILES_DIRS = []

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Django 5+ storage configuration: define default/media + staticfiles via STORAGES.
CLOUDINARY_URL = os.getenv('CLOUDINARY_URL', '')
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
    'default': {
        'BACKEND': (
            'core.custom_storage.CloudinaryStorage'
            if CLOUDINARY_URL
            else 'django.core.files.storage.FileSystemStorage'
        ),
    },
}

# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND') or (
    'django.core.mail.backends.smtp.EmailBackend'
    if os.getenv('EMAIL_HOST_USER')
    else 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'AASTU SU <noreply@aastusu.com>')

# Frontend URL for password reset links
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cache configuration used by analytics dashboard response caching.
ANALYTICS_DASHBOARD_CACHE_TTL = int(os.getenv('ANALYTICS_DASHBOARD_CACHE_TTL', '600'))
CACHES = {
    'default': {
        'BACKEND': os.getenv('DJANGO_CACHE_BACKEND', 'django.core.cache.backends.locmem.LocMemCache'),
        'LOCATION': os.getenv('DJANGO_CACHE_LOCATION', 'aastu-su-cache'),
    }
}


# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'core.renderers.CoreJSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'core.parsers.CoreJSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.CorePagination',
    'EXCEPTION_HANDLER': 'core.exceptions.core_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'core.schema.AASTUAutoSchema',
}



SPECTACULAR_SETTINGS = {
    'TITLE': 'AASTU Student Union API',
    'DESCRIPTION': 'API documentation for the AASTU Student Union website backend.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'TAGS': [
        {'name': 'Authentication', 'description': 'User login, registration and password management endpoints.'},
    ],
    'COMPONENT_SPLIT_PATCH': True,
    'COMPONENT_SPLIT_REQUEST': True,
    'ENUM_NAME_OVERRIDES': {
        'BookingStatusEnum': [
            ('pending', 'Pending Approval'),
            ('approved', 'Approved'),
            ('cancelled', 'Cancelled'),
        ],
        'ClubStatusEnum': [
            ('active', 'Active'),
            ('pending', 'Pending Approval'),
            ('rejected', 'Rejected'),
        ],
        'EventStatusEnum': [
            ('upcoming', 'Upcoming Event'),
            ('live-now', 'Happening Now'),
            ('archived', 'Past Event'),
        ],
        'VenueStatusEnum': [
            ('active', 'Active'),
            ('maintenance', 'Maintenance'),
            ('inactive', 'Inactive'),
        ],
    },
    'PARSER_WHITELIST': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'displayOperationId': False,
        'defaultModelsExpandDepth': -1,
        'defaultModelExpandDepth': 1,
        'docExpansion': 'none',
        'filter': True,
        'persistAuthorization': True,
    },
}





# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]   

# Add production frontend origin for CORS
CORS_ALLOWED_ORIGINS.append("https://aastu-student-union-web.vercel.app")

# Simple JWT Configuration
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    # Allow explicit JWT signing key via env var; fall back to Django SECRET_KEY
    'SIGNING_KEY': os.getenv('SIMPLE_JWT_SIGNING_KEY', SECRET_KEY),
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=60),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# Warn if the JWT signing key is suspiciously short — do not raise here to avoid
# breaking startup, but surface an obvious warning for operators.
import warnings
_jwt_key = SIMPLE_JWT.get('SIGNING_KEY')
try:
    if _jwt_key and len(_jwt_key) < 32:
        warnings.warn('SIMPLE_JWT SIGNING_KEY is shorter than 32 characters — rotate to a stronger key.', RuntimeWarning)
except Exception:
    # defensive: do not allow settings import to fail
    pass

# Jazzmin Configuration
JAZZMIN_SETTINGS = {
    "site_title": "AASTU SU Admin",
    "site_header": "AASTU SU Admin",
    "site_brand": "SU Admin",
    "site_logo": None,  # Set to None if logo file doesn't exist to avoid broken image
    "welcome_sign": "Welcome to AASTU Student Union Admin",
    "copyright": "AASTU Student Union",
    # Fixed: Only use one search model or remove it to fix "too many search bars"
    "search_model": ["users.User"], 
    "user_avatar": None,
    # Main menu customization
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "http://localhost:3000", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "show_ui_builder": False,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.Group": "fas fa-users",
        "users.User": "fas fa-user-graduate",
        "clubs.Club": "fas fa-handshake",
        "venues.Venue": "fas fa-building",
        "bookings.Booking": "fas fa-calendar-check",
        "events.Event": "fas fa-calendar-alt",
        "announcements.Announcement": "fas fa-bullhorn",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    # Use classic popup for related-object (+) forms to avoid compressed modal layout.
    "related_modal_active": False,
    "use_google_fonts_cdn": True,
    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_remove_offset": False,
    "sidebar_link_nav_legacy_style": False,
    "sidebar_link_nav_flat_style": False,
    "theme": "default",
    "default_theme_mode": "auto",
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}


# Email Configuration (for password reset)
