# Generated by Django 5.2.13 on 2026-04-16 07:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('category', models.CharField(choices=[('academic', 'Academic Updates'), ('social', 'Social Events'), ('union', 'Student Union News')], default='union', max_length=20)),
                ('author_name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
                ('procedure_steps', models.JSONField(default=list)),
                ('content_paragraphs', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
