# Generated by Django 5.2.13 on 2026-04-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_remove_announcement_image_url_announcement_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='content_paragraphs',
        ),
        migrations.AddField(
            model_name='announcement',
            name='body',
            field=models.TextField(default='', help_text='Rich text content (HTML)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='procedure_steps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
