# Generated by Django 5.2.12 on 2026-04-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_remove_announcement_content_paragraphs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
