# Generated by Django 5.2.12 on 2026-04-18 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_announcementcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='summary',
        ),
    ]
