# Generated by Django 5.2.13 on 2026-04-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_remove_announcement_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether the announcement is published and visible to the public'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='author_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
