# Generated by Django 5.2.13 on 2026-05-05 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_announcement_is_published_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_published'], name='announcemen_is_publ_44200e_idx'),
        ),
    ]
