# Generated by Django 5.2.13 on 2026-04-16 07:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('category_label', models.CharField(max_length=100)),
                ('location_label', models.CharField(max_length=255)),
                ('logo_label', models.CharField(blank=True, max_length=10)),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('about', models.JSONField(default=list)),
                ('advisor_name', models.CharField(blank=True, max_length=255)),
                ('links', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
