# Generated by Django 5.2.13 on 2026-04-16 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_led', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['status'], name='clubs_club_status_23d2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['name'], name='clubs_club_name_657a0c_idx'),
        ),
    ]
