# Generated by Django 5.2.13 on 2026-04-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_remove_club_cover_image_url_club_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='about',
        ),
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(default='', help_text='Rich text content (HTML)'),
            preserve_default=False,
        ),
    ]
