# Generated by Django 5.2.12 on 2026-04-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_remove_club_about_club_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='links',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
