# Generated by Django 5.2.12 on 2026-04-18 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_alter_club_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Club Category',
                'verbose_name_plural': 'Club Categories',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='club',
            name='category_label',
        ),
        migrations.AddField(
            model_name='club',
            name='advisor_department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='advisor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='club',
            name='advisor_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='president_department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='president_dorm_block',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='president_dorm_room',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='president_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='club',
            name='president_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='club',
            name='president_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='president_student_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='clubs.clubcategory'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['category'], name='clubs_club_categor_0a0025_idx'),
        ),
    ]
