# Generated by Django 5.2.12 on 2026-04-18 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_clubcategory_remove_club_category_label_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='advisor_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_advisor_of', to='core.department'),
        ),
        migrations.AlterField(
            model_name='club',
            name='president_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_president_of', to='core.department'),
        ),
    ]
