# Generated by Django 5.2.12 on 2026-04-18 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_alter_club_advisor_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='president_department',
        ),
        migrations.RemoveField(
            model_name='club',
            name='president_dorm_block',
        ),
        migrations.RemoveField(
            model_name='club',
            name='president_dorm_room',
        ),
        migrations.RemoveField(
            model_name='club',
            name='president_email',
        ),
        migrations.RemoveField(
            model_name='club',
            name='president_full_name',
        ),
        migrations.RemoveField(
            model_name='club',
            name='president_phone',
        ),
        migrations.RemoveField(
            model_name='club',
            name='president_student_id',
        ),
        migrations.AlterField(
            model_name='club',
            name='president',
            field=models.ForeignKey(blank=True, help_text='The registered User who leads this club. Contact info is pulled from their profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_led', to=settings.AUTH_USER_MODEL),
        ),
    ]
