# Generated by Django 5.2.13 on 2026-04-18 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_remove_club_president_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='advisor_department',
        ),
        migrations.RemoveField(
            model_name='club',
            name='advisor_email',
        ),
        migrations.RemoveField(
            model_name='club',
            name='advisor_name',
        ),
        migrations.RemoveField(
            model_name='club',
            name='advisor_phone',
        ),
        migrations.AddField(
            model_name='club',
            name='advisor',
            field=models.ForeignKey(blank=True, help_text='The registered User who advises this club.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_advised', to=settings.AUTH_USER_MODEL),
        ),
    ]
