# Generated by Django 5.2.13 on 2026-04-27 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_remove_club_advisor_department_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='department',
            field=models.ForeignKey(blank=True, help_text='The department this club belongs to (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='core.department'),
        ),
    ]
