# Generated by Django 5.2.12 on 2026-05-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_club_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='proposal_file',
            field=models.FileField(blank=True, null=True, upload_to='clubs/proposals/'),
        ),
        migrations.AddField(
            model_name='club',
            name='show_proposal',
            field=models.BooleanField(default=False),
        ),
    ]
