# Generated by Django 5.2.12 on 2026-04-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_equipment_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='guidelines_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_slots',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
