# Generated by Django 5.2.12 on 2026-04-30 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_acknowledged_at_booking_end_date_and_more'),
        ('events', '0010_rename_summary_event_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_booking', to='events.event'),
        ),
    ]
