# Generated by Django 5.2.13 on 2026-05-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'permissions': [('approve_booking', 'Can approve booking requests'), ('reject_booking', 'Can reject booking requests')], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
    ]
